[java.git]
group_id = "de.juliansiebert"
artifact_id = "buffy-test-java"
url = "https://github.com/julian-siebert/buffy-test-java"
remote = "git@github.com:julian-siebert/buffy-test-java.git"
branch = "main"

[java.git.scm]
connection = "scm:git:git://github.com/julian-siebert/buffy-test-java.git"
url = "https://github.com/julian-siebert/buffy-test-java"
